language: php
sudo: required
dist: trusty

jobs:
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4snapshot"
    - php: "nightly"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

script:
  - git fetch --unshallow
  - make deps
  - make dist
  - build/eventum.phar --version

# vim:ts=2:sw=2:et
